export const DEFAULT_QUANTITY = 5;
export const MIN_QUANTITY = 1;
export const MAX_QUANTITY = 100;

export const TOOL_METADATA = {
  title: 'UUID / GUID Generator',
  description: 'Generate unique UUID (v4 and v1) strings instantly. Configure count, casing, and hyphens with local browser execution.',
  slug: 'uuid-generator',
  category: 'developer-tools',
};

export const TOOL_FAQS = [
  {
    question: 'What is a UUID?',
    answer: 'A UUID (Universally Unique Identifier) is a 128-bit number used to uniquely identify information in computer systems without significant central coordination.',
  },
  {
    question: 'What is the difference between UUID v1 and v4?',
    answer: 'UUID v1 is generated using the host computer\'s MAC address and a timestamp, making it time-based. UUID v4 is generated using random numbers, making it highly random and more private as it doesn\'t expose physical machine details.',
  },
  {
    question: 'Are these UUIDs safe to use in database keys?',
    answer: 'Yes. The chance of a collision (generating duplicate UUIDs) is virtually zero, making them excellent choices for database keys, transaction IDs, and identifiers.',
  },
  {
    question: 'What is a GUID and how does it differ from a UUID?',
    answer: 'GUID stands for Globally Unique Identifier, which is Microsoft\'s implementation of the UUID standard. In practice, GUIDs and UUIDs are identical in structure and represent the same standard, though the term GUID is more common in Microsoft environments (like C#, SQL Server, and Active Directory).',
  },
  {
    question: 'Could two generated UUIDs ever collide?',
    answer: 'While a collision is mathematically possible, the probability is astronomical. For UUID v4, the number of possible unique keys is 2^122 (approximately 5.3 undecillion). To put this in perspective, if you generated 1 billion UUIDs per second for 85 years, the chance of a single collision would be about 50%.',
  },
  {
    question: 'Does this generator store my generated UUIDs?',
    answer: 'No. The Jumpytools UUID generator executes entirely client-side using standard Web Crypto APIs available in modern browsers. No server calls are made, and your generated keys are never saved, keeping them secure for API credentials, tokens, or private database IDs.',
  },
];

export const TOOL_ABOUT = [
  'A Universally Unique Identifier (UUID), also referred to as a Globally Unique Identifier (GUID) in Windows ecosystems, is a 128-bit label used to uniquely tag resources across computer systems. The beauty of the UUID standard is that it allows independent systems to generate identifiers without needing a central coordinator or registrar. This is incredibly useful for database primary keys, session tokens, transaction logs, and distributed storage systems where ID collisions must be prevented.',
  'Understanding UUID Formats and Versions:',
  'A standard UUID is represented as a 36-character string consisting of 32 hexadecimal characters grouped by hyphens in an 8-4-4-4-12 pattern (e.g., 123e4567-e89b-12d3-a456-426614174000). Our generator lets you produce both Version 4 and Version 1 identifiers depending on your requirements:',
  '• Version 4 (Randomly Generated): The most widely used type of UUID. Out of its 128 bits, 122 bits are generated completely at random, while 6 bits are reserved for standard version indicators. This is ideal for most applications because it contains no traceable computer identifiers or creation timestamps, ensuring maximum privacy.',
  '• Version 1 (Time and Node-Based): Generated by extracting the computer\'s high-resolution system timestamp combined with its unique hardware MAC address (referred to as the node). While useful for systems that require ordering or sorting IDs by creation time, v1 UUIDs expose the physical hardware MAC address and exact creation timestamp, which can be a privacy concern in public APIs.',
  'Common Developer Use Cases:',
  '• Database Primary Keys: Replace auto-incrementing integer IDs with UUIDs. This prevents external users from guessing your total user count or predicting resources via simple sequential ID guessing (sequential enumeration attacks).',
  '• Microservices Integration: Assign a unique Correlation ID or Request ID to incoming API requests to trace logs across complex distributed services.',
  '• Temporary Tokens: Generate random, non-guessable confirmation keys, password reset links, or session tokens client-side.',
  'Zero-Server Privacy Guarantee:',
  'Security is paramount when generating keys that might be used for authorization tokens or critical database indexes. Unlike other online generators that make network requests to a backend server to generate random strings, our generator utilizes the browser\'s secure `crypto.getRandomValues()` API. All operations complete inside your browser sandbox, ensuring your generated values are 100% private and protected from network eavesdropping.',
];

